version: '3.7'

services:
  web:
    build: ./
    container_name: test_task
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env.dev


  db:
    image: postgres:12
    container_name: test_task_db
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.dev


volumes:
  pg_data:
