# Generated by Django 4.0.6 on 2022-07-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postdislike_options_alter_postlike_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdislike',
            name='disliked_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='liked_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
