# Generated by Django 4.0.6 on 2022-07-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_postdislike_disliked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postuserview',
            name='viewed_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
