# Generated by Django 4.0.6 on 2022-07-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='last_request',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
